// Code generated by "dataclass -type InternalTarget -field Path string|Linum int -output parameter_dataclass_generated.go"; DO NOT EDIT.

package parse

type InternalTarget interface {
	Path() string
	Linum() int
}
type internalTarget struct {
	path  string
	linum int
}

func (s *internalTarget) Path() string { return s.path }
func (s *internalTarget) Linum() int   { return s.linum }
func NewInternalTarget(
	path string,
	linum int,
) InternalTarget {
	return &internalTarget{
		path:  path,
		linum: linum,
	}
}
