// Code generated by "goconfig -field GHCommand string -option -output config_generated.go"; DO NOT EDIT.

package gh

type ConfigItem[T any] struct {
	modified     bool
	value        T
	defaultValue T
}

func (s *ConfigItem[T]) Set(value T) {
	s.modified = true
	s.value = value
}
func (s *ConfigItem[T]) Get() T {
	if s.modified {
		return s.value
	}
	return s.defaultValue
}
func (s *ConfigItem[T]) Default() T {
	return s.defaultValue
}
func (s *ConfigItem[T]) IsModified() bool {
	return s.modified
}
func NewConfigItem[T any](defaultValue T) *ConfigItem[T] {
	return &ConfigItem[T]{
		defaultValue: defaultValue,
	}
}

type Config struct {
	GHCommand *ConfigItem[string]
}
type ConfigBuilder struct {
	gHCommand string
}

func (s *ConfigBuilder) GHCommand(v string) *ConfigBuilder {
	s.gHCommand = v
	return s
}
func (s *ConfigBuilder) Build() *Config {
	return &Config{
		GHCommand: NewConfigItem(s.gHCommand),
	}
}

func NewConfigBuilder() *ConfigBuilder { return &ConfigBuilder{} }
func (s *Config) Apply(opt ...ConfigOption) {
	for _, x := range opt {
		x(s)
	}
}

type ConfigOption func(*Config)

func WithGHCommand(v string) ConfigOption {
	return func(c *Config) {
		c.GHCommand.Set(v)
	}
}
